# security-demos.yaml
# Exposes two apps on lab-kube-node2 using hostPort 8080 and 8081

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-vulnerablewebapp
  labels:
    app: DVWA_VulnerableWebApp
    app.kubernetes.io/part-of: security-demos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DVWA_VulnerableWebApp
  template:
    metadata:
      labels:
        app: DVWA_VulnerableWebApp
        app.kubernetes.io/part-of: security-demos
    spec:
      nodeName: lab-kube-node2
      containers:
      - name: dvwa
        image: andrefernandes86/c1as-demo-dvwa
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          hostPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-vulnerablewebapp
  labels:
    app: DVWA_VulnerableWebApp
    app.kubernetes.io/part-of: security-demos
spec:
  selector:
    app: DVWA_VulnerableWebApp
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: malware-samples
  labels:
    app: Malware_Samples
    app.kubernetes.io/part-of: security-demos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Malware_Samples
  template:
    metadata:
      labels:
        app: Malware_Samples
        app.kubernetes.io/part-of: security-demos
    spec:
      nodeName: lab-kube-node2
      containers:
      - name: malware-samples
        image: andrefernandes86/tools-malware-samples
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          hostPort: 8081
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: malware-samples
  labels:
    app: Malware_Samples
    app.kubernetes.io/part-of: security-demos
spec:
  selector:
    app: Malware_Samples
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
