version: "3.9"

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: always
    ports:
      - "80:8080"
    user: "1000:1000"
    working_dir: /app/backend/data
    environment:
      WEBUI_SECRET_KEY: "f4c9f84a8d6a7e2f5c34a9c9e5db7a68f21a5cbd8c6d47e3b82d1d0d2f9a7c3e"
    volumes:
      - /mnt/data/owui:/app/backend/data
    security_opt:
      - no-new-privileges:true
