version: "3.9"

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: always
    ports:
      - "80:8080"
    user: "1000:1000"   # makes container run as your host user, so files in /mnt/data/owui aren’t owned by root
    volumes:
      - /mnt/data/owui:/app/backend/data
    security_opt:
      - no-new-privileges:true
